### ISSUE TITLE
run init script fails to start

### ISSUE THREAD

**Issue by spuder** [lusis/chef-kibana#106]
I find that on first provision, the run init script always fails. 

However if you got to localhost:5601, the service is running. 

```bash
 Recipe: nd-kibana::default
         * runit_service[kibana] action restart

           ================================================================================
           Error executing action `restart` on resource 'runit_service[kibana]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /usr/bin/sv restart /etc/service/kibana ----
           STDOUT: fail: /etc/service/kibana: unable to change to service directory: file does not exist
           STDERR:
           ---- End output of /usr/bin/sv restart /etc/service/kibana ----
           Ran /usr/bin/sv restart /etc/service/kibana returned 1

           Cookbook Trace:
           ---------------

           /tmp/kitchen/cookbooks/runit/libraries/provider_runit_service.rb:277:in `block in <class:RunitService>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cookbooks/nd-kibana/recipes/default.rb

            44: runit_service 'kibana' do
            45:   options(
            46:     user: "#{kibana_user}",
            47:     home: "#{node['kibana']['install_dir']}/current"
            48:   )
            49:   cookbook 'kibana_lwrp'
            50:   action :create
        51:   subscribes :restart, "template[#{kibana_config}]", :delayed
            52: end
            53:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cookbooks/nd-kibana/recipes/default.rb:44:in `from_file'

           runit_service("kibana") do
             provider Chef::Provider::RunitService

             updated true
             supports {:restart=>true, :reload=>true, :status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "kibana"
             pattern "kibana"
             status_command "/usr/bin/sv status /etc/service"
             sv_bin "/usr/bin/sv"
             sv_dir "/etc/sv"
             service_dir "/etc/service"
             lsb_init_dir "/etc/init.d"
             options {:user=>"kibana", :home=>"/opt/kibana/current"}
             log true
             cookbook "kibana_lwrp"
         restart_on_update true
             run_template_name "kibana"
             log_template_name "kibana"
             check_script_template_name "kibana"
             finish_script_template_name "kibana"
             sv_templates true
             service_mirror # Declared in

           service("kibana") do
             provider Chef::Provider::Service::Simple
             action [:nothing]
             supports {:restart=>true, :reload=>true, :status=>true}
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             service_name "kibana"
             pattern "kibana"
             start_command "/usr/bin/sv start /etc/service/kibana"

             status_command "/usr/bin/sv status /etc/service/kibana"
             restart_command "/usr/bin/sv restart /etc/service/kibana"
           end

             declared_type :runit_service
             cookbook_name :"nd-kibana"
             recipe_name "default"
           end


         * service[nginx] action reload
           - reload service service[nginx]

       Running handlers:
       [2015-11-29T01:41:20+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-11-29T01:41:20+00:00] ERROR: Exception handlers complete
       Chef Client failed. 58 resources updated in 04 minutes 41 seconds
       [2015-11-29T01:41:20+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-11-29T01:41:20+00:00] ERROR: runit_service[kibana] (nd-kibana::default line 44) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /usr/bin/sv restart /etc/service/kibana ----
       STDOUT: fail: /etc/service/kibana: unable to change to service directory: file does not exist
       STDERR:
       ---- End output of /usr/bin/sv restart /etc/service/kibana ----
       Ran /usr/bin/sv restart /etc/service/kibana returned 1
       [2015-11-29T01:41:21+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Here is the recipe that reproduces this. The key is the "subscribes" line on the runit_service resource

```ruby
install_type  = node['kibana']['install_type'] # 'file' or 'git'
kibana_user   = node['kibana']['user']
docroot       = "#{node['kibana']['install_dir']}/current/kibana"
kibana_config = "#{node['kibana']['install_dir']}/current/#{node['kibana'][install_type]['config']}"
es_server     = "#{node['kibana']['es_scheme']}#{node['kibana']['es_server']}:#{node['kibana']['es_port']}"

# Create kibana user and group
kibana_user 'kibana' do
  user "#{kibana_user}"
  group "#{kibana_user}"
  home '/opt/kibana'
  action :create
end

# Install kibana from 'file' or 'git'
kibana_install 'kibana' do
  user "#{kibana_user}"
  group "#{kibana_user}"
  install_dir '/opt/kibana'
  install_type "#{install_type}"
  action :create
end

# Create kibana.yml from template from base cookbook
template "#{kibana_config}" do
  source node['kibana']["#{install_type}"]['config_template']
  cookbook node['kibana']["#{install_type}"]['config_template_cookbook']
  mode '0644'
  user "#{kibana_user}"
  group "#{kibana_user}"
  variables(
    index: node['kibana']['config']['kibana_index'],
    port: node['kibana']['java_webserver_port'],
    elasticsearch: "#{es_server}",
    default_route: node['kibana']['config']['default_route'],
    panel_names:  node['kibana']['config']['panel_names']
  )
  action :create
end

include_recipe 'runit::default'

# Start kibana service, Only works if install_type = 'file', not 'git'
runit_service 'kibana' do
  options(
    user: "#{kibana_user}",
    home: "#{node['kibana']['install_dir']}/current"
  )
  cookbook 'kibana_lwrp'
  action :create
  subscribes :restart, "template[#{kibana_config}]", :delayed #****** <---- THIS IS THE CULPRIT ******#
end

# Create nginx proxy to forward port 5601 to 80.  Uses the template in the base cookbook
# See https://github.com/lusis/chef-kibana/tree/master/templates/default
kibana_web 'kibana' do
  type 'nginx'
  es_server "#{es_server}"
  server_name 'kitchen-kibana.localhost' #TODO change to variable
  server_aliases ["#{node['hostname']}","#{node['fqdn']}"]
  template "kibana-nginx_#{install_type}.conf.erb"
  action :create
end
```

And here is the kitchen file

```yaml
---
driver:
  name: vagrant
  network:
  - ["forwarded_port", { guest: 5601, host: 5601 }]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[nd-kibana::default]
    attributes:
      java:
        install_flavor: "oracle"
        jdk_version: "8"
        oracle:
          accept_oracle_download_terms: true
      kibana:
        es_server: "swat-elasticsearchpool.example.com"

```

**Comment by spuder** [comment]
Update, 

Just tried the kibana_lwrp::install recipe example with the same results. 

I suspect that there is a race condition where the service isn't ready in time

**Comment by spuder** [comment]
Running chef twice works


```ruby
         Recipe: libarchive::default
           * apt_package[libarchive-dev] action upgrade (up to date)
           * chef_gem[ffi-libarchive] action install (up to date)
           * directory[/opt/kibana] action create (up to date)
           * apt_package[libarchive-dev] action nothing (skipped due to action :nothing)
           * chef_gem[ffi-libarchive] action install (up to date)
           * remote_file[/tmp/kitchen/cache/kibana_kibana_4.1.3-linux-x64_kibana.tar.gz] action create (up to date)
           * libarchive_file[kibana_kibana_4.1.3-linux-x64_kibana.tar.gz] action extract (skipped due to not_if)
           * link[/opt/kibana/current] action create (up to date)
           - create resource kibana
       Recipe: nd-kibana::default
         * template[/opt/kibana/current/config/kibana.yml] action create (up to date)
       Recipe: runit::default
         * service[runit] action nothing (skipped due to action :nothing)
         * execute[start-runsvdir] action nothing (skipped due to action :nothing)
         * execute[runit-hup-init] action nothing (skipped due to action :nothing)
         * apt_package[runit] action install (up to date)
       Recipe: <Dynamically Defined Resource>
         * service[kibana] action nothing (skipped due to action :nothing)
       Recipe: nd-kibana::default
         * runit_service[kibana] action enable
           * directory[/etc/sv/kibana] action create (up to date)
           * template[/etc/sv/kibana/run] action create (up to date)
           * directory[/etc/sv/kibana/log] action create (up to date)
           * directory[/etc/sv/kibana/log/main] action create (up to date)
           * directory[/var/log/kibana] action create (up to date)
           * template[/etc/sv/kibana/log/config] action create (up to date)
           * link[/var/log/kibana/config] action create (up to date)
           * template[/etc/sv/kibana/log/run] action create (up to date)
           * directory[/etc/sv/kibana/env] action create (up to date)
           * ruby_block[zap extra env files for kibana service] action run (skipped due to only_if)
           * directory[/etc/sv/kibana/control] action create (up to date)
           * link[/etc/init.d/kibana] action create (up to date)
           * file[/etc/sv/kibana/down] action nothing (skipped due to action :nothing)
           * directory[/etc/sv/kibana] action create (up to date)
           * template[/etc/sv/kibana/run] action create (up to date)
           * directory[/etc/sv/kibana/log] action create (up to date)
           * directory[/etc/sv/kibana/log/main] action create (up to date)
           * directory[/var/log/kibana] action create (up to date)
           * template[/etc/sv/kibana/log/config] action create (up to date)
           * link[/var/log/kibana/config] action create (up to date)
           * template[/etc/sv/kibana/log/run] action create (up to date)
           * directory[/etc/sv/kibana/env] action create (up to date)
           * ruby_block[zap extra env files for kibana service] action run (skipped due to only_if)
           * directory[/etc/sv/kibana/control] action create (up to date)
           * link[/etc/init.d/kibana] action create (up to date)
           * file[/etc/sv/kibana/down] action nothing (skipped due to action :nothing)
           * directory[/etc/service] action create (up to date)
           * link[/etc/service/kibana] action create
             - create symlink at /etc/service/kibana to /etc/sv/kibana
           * ruby_block[wait for kibana service socket] action run
             - execute the ruby block wait for kibana service socket
```

Comparing the runlist of the first converge vs the second converge

```
link[/etc/init.d/kibana] action create
file[/etc/sv/kibana/down] action nothing
runit_service[kibana] action restart  <------FAIL Why is this running before the link ? The subscribes had timer :delayed so it should have run at the end
```

```
link[/etc/init.d/kibana] action create
file[/etc/sv/kibana/down] action nothing
directory[/etc/service] action create     <--- huh? Why does chef run the directory this time, and not the service? 
link[/etc/service/kibana] action create
```

**Comment by spuder** [comment]
Possibly related

https://github.com/hw-cookbooks/runit/issues/142

**Comment by martinb3** [comment]
Looks like we should pin to a version that's at least equal to or greater than the fixed runit cookbook version. Thanks!

**Comment by spuder** [comment]
Spun up a new test kitchen today. I can no longer reproduce this. I suspect that the version of runit in the supermarket (1.7.6) finally fixed this. (Initially reported against runit 1.7.4)
