### ISSUE TITLE
in 3.0.0 kibana_web lwrp default behavior changed and action :create is broken

### ISSUE THREAD

**Issue by tbunnyman** [lusis/chef-kibana#112]
I updated to 3.0.0 and now the default action on `kibana_web` is `:nothing`, breaking my tests since nginx is never installed or configured
I manually changed my usage to `action :create` and this breaks the converge with the following output.

```
         * kibana_web[kibana] action create

           ================================================================================
           Error executing action `create` on resource 'kibana_web[kibana]'
           ================================================================================

           NoMethodError
           -------------
           No resource or method named `notifying_block' for `Chef::Provider::KibanaWeb ""'

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/web.rb:38:in `block (2 levels) in <class:KibanaWeb>'
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/web.rb:37:in `block in <class:KibanaWeb>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/logging/recipes/kibana.rb

            66: kibana_web 'kibana' do
            67:   type        lazy { node['kibana']['webserver'] }
            68:   docroot     docroot
            69:   es_server   node['kibana']['es_server']
            70:   kibana_port node['kibana']['java_webserver_port']
            71:   template    'kibana-nginx_file.conf.erb'
            72:   action      :create
            73: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/logging/recipes/kibana.rb:66:in `from_file'

           kibana_web("kibana") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :kibana_web
             cookbook_name "logging"
             recipe_name "kibana"
             type #<Chef::DelayedEvaluator:0x000000050cf940@/tmp/kitchen/cache/cookbooks/logging/recipes/kibana.rb:67>
             docroot "/opt/kibana/current/kibana"
             es_server "server-centos-67"
             kibana_port 5601
             template "kibana-nginx_file.conf.erb"
           end
```

test kitchen
chef 12.6.0
centos 6.7

**Comment by martinb3** [comment]
Thank you for reporting this. Looks like I missed two poise-related issues when removing it. Fixing and releasing now.

**Comment by martinb3** [comment]
Please give 3.0.1 a try and let us know! Thanks again for the report!
