### ISSUE TITLE
Unable to install undefined method looks like attributes are not being set

### ISSUE THREAD

**Issue by qgriffith** [lusis/chef-kibana#121]
I am using include_recipe 'kibana_lwrp::install' in my recipe and kibana fails to install. It was working prior to a chef upgrade. It looks like the attributes are not being read into the recipe for some reason

Chef Version 12.12.15

           ```
================================================================================
           Error executing action `create` on resource 'kibana_web[kibana]'
           ================================================================================

           NoMethodError
           -------------
           undefined method `[]' for nil:NilClass

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/nginx/recipes/ohai_plugin.rb:27:in `from_file'
           /tmp/kitchen/cache/cookbooks/nginx/recipes/default.rb:21:in `from_file'
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/web.rb:70:in `block (2 levels) in <class:KibanaWeb>'
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/web.rb:38:in `block in <class:KibanaWeb>'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/kibana_lwrp/recipes/install.rb

            90: kibana_web 'kibana' do
            91:   type lazy { node['kibana']['webserver'] }
            92:   docroot docroot
            93:   es_server node['kibana']['es_server']
            94:   kibana_port node['kibana']['java_webserver_port']
            95:   template 'kibana-nginx_file.conf.erb'
            96:   not_if { node['kibana']['webserver'] == '' }
            97: end

           Compiled Resource:
```

**Comment by martinb3** [comment]
Hi there -- this appears to be coming from a dependent cookbook where there's some required ohai attributes that seem to be missing: https://github.com/miketheman/nginx/blob/2.7.x/recipes/ohai_plugin.rb#L27

Do you happen to be doing anything interesting with the ohai tool? Could you also let us know if it worked with the latest nginx cookbook or if that was also bumped to a newer version as part of the changes you're trying to implement?

**Comment by qgriffith** [comment]
Thanks for the quick response. I ended up making the recipe depend on ohai version 4.0 to fix the issue.

**Comment by martinb3** [comment]
Great! Glad it works :)

**Comment by pgrzesik** [comment]
Hello, I'm not sure if I should write in this closed question, however I got the same issue. Could you please share your solution @qgriffith ?
