### ISSUE TITLE
kibana_web is notifying service[nginx] when it doesn't exist

### ISSUE THREAD

**Issue by martinb3** [lusis/chef-kibana#79]
Even with this earlier in my chef run:
```
Recipe: nginx::default       
  * service[nginx] action start[2014-12-24T20:47:45+00:00] INFO: Processing service[nginx] action start (nginx::default line 24)       
 (up to date)    
```
I'm getting this when using `kibana_web` on v1.3.2 of the cookbook:

```
    ================================================================================       
    Error executing action `create` on resource 'kibana_web[kibana]'       
    ================================================================================       
           
    Chef::Exceptions::ResourceNotFound       
    ----------------------------------       
    resource template[/etc/nginx/sites-available/kibana] is configured to notify resource service[nginx] with action reload, but service[nginx] cannot be found in the resource collection. template[/etc/nginx/sites-available/kibana] is defined in /tmp/kitchen/cache/cookbooks/kibana/providers/web.rb:58:in `block in class_from_file'       
           
    Resource Declaration:       
    ---------------------       
    # In /tmp/kitchen/cache/cookbooks/elkstack/recipes/kibana.rb       
           
            67: kibana_web 'kibana' do
            68:   type node['kibana']['webserver']
            69:   docroot "#{node['kibana']['install_dir']}/current"
            70:   template_cookbook node['kibana']['nginx']['template_cookbook']
           
        71:   template node['kibana']['nginx']['template']
            72:   es_server node['kibana']['es_server']
            73:   es_port node['kibana']['es_port']
            74:   not_if { node['kibana']['webserver'].empty? }
            75: end
            76: # end replaces 'kibana::install'
            77: 
            78: # monitoring
       
            79: include_recipe 'elkstack::kibana_monitoring'
           
           Compiled Resource:
           ------------------
           
       # Declared in /tmp/kitchen/cache/cookbooks/elkstack/recipes/kibana.rb:67:in `from_file'
           
           kibana_web("kibana") do
             action :create
             retries 0
             retry_delay 2
             guard_interpreter :default
             cookbook_name "elkstack"
             recipe_name "kibana"
             type "nginx"
             docroot "/opt/kibana/current"
             template_cookbook "elkstack"
             template "kibana-nginx.conf.erb"
             es_server "127.0.0.1"
             es_port "9200"
             server_name "kibana.localhost"
             server_aliases ["kibana"]
             listen_address "0.0.0.0"
             listen_port "80"
             es_scheme "http://"
       
             not_if { #code block }
           end
```

I realize the cookbook has moved on to 1.4 and the newer kibana, but I don't see any updates to the nginx cookbook since this started happening, so I'm trying to narrow it down to a change in the kibana cookbook (I'm pretty sure it's the addition of `use_inline_resources`).

**Comment by Daegalus** [comment]
Just a heads up, I am experiencing this with v2.0.0 on the supermarket. Same error. For now I will try Martin's old workaround and see if it works for me.

**Comment by damienjoldersma** [comment]
I just wanted to second @Daegalus comment, workign with v2.0.4, @martinb3 fix worked for me too, except that I had to make the dummy service in libraries/web.rb instead of providers/web.rb, around line 72, just above the nginx template.

**Comment by lerman** [comment]
Any update on this? I'm getting the same error

**Comment by MrPink** [comment]
getting the same with 2.0.4

**Comment by dooblem** [comment]
Same here, working fine with @damienjoldersma workaround.
Can you patch please ?

**Comment by martinb3** [comment]
Due to the renamed cookbook, we can't release under the old name. So this is fixed for new versions, but there's not really an easy way to release the old one.
