### ISSUE TITLE
Failed install kibana 3 using kibana_install

### ISSUE THREAD

**Issue by dieend** [lusis/chef-kibana#96]
Here is the stacktrace
```
================================================================================
Error executing action `extract` on resource 'libarchive_file[kibana_3.1.2_web.tar.gz]'
================================================================================
 
 
LoadError
---------
cannot load such file -- ffi
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/libarchive/libraries/helper.rb:31:in `require'
/var/lib/aws/opsworks/cache.stage2/cookbooks/libarchive/libraries/helper.rb:31:in `extract'
/var/lib/aws/opsworks/cache.stage2/cookbooks/libarchive/providers/file.rb:18:in `block in class_from_file'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/kibana/providers/install.rb
 
67:       res = libarchive_file "kibana_#{kb_args[:file_version]}_#{kb_args[:name]}.tar.gz" do
68:         path "#{Chef::Config[:file_cache_path]}/kibana_#{kb_args[:file_version]}_#{kb_args[:name]}.tar.gz"
69:         extract_to kb_args[:install_dir]
70:         owner kb_args[:user]
71:         action [:extract]
72:       end
73:       new_resource.updated_by_last_action(res.updated_by_last_action?)
 
 
 
Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/kibana/providers/install.rb:67:in `block in class_from_file'
 
libarchive_file("kibana_3.1.2_web.tar.gz") do
action [:extract]
retries 0
retry_delay 2
cookbook_name "my_cookbook"
path "/var/lib/aws/opsworks/cache.stage2/kibana_3.1.2_web.tar.gz"
extract_to "/opt/kibana"
owner "www-data"
mode 493
end
 ```

**Comment by martinb3** [comment]
I believe with Kibana 4, this is no longer an issue. I'm going to close, but please comment or re-open if it's still an issue. Thank you!
